name: Backend Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone or pull the changes
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd transfer-project
          git pull
          
    - name: Build and run container
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd transfer-project/backend
            docker build . -t inatsuz/personal-images:transfer-app-backend
            docker container stop transfer-app-backend
            docker container prune -f
            docker container run --name transfer-app-backend -e DB_HOST='vraminhos.com' -d -p 443:443 -p 80:80 inatsuz/personal-images:transfer-app-backend
